language: go
go: '1.11.x'
git:
  depth: 1
services:
- docker
- redis-server
env:
  global:
  - secure: 2I0+pzIvKKi9RbmAjOBCS4gQFf7+KTDLIcGpoTPsvMUG6XMRiv5WUV0GWGRtKEpBs/iHOEOL2OkCI1SsN/mMyK/HcRLyotVDht12KILhmQxc5+ApawcaoU0LM4pnMthOztm3y+jX58F8NBqksLt3JCSinLr4eX/wTjsaJnjnGjncACFEiXUZK2566rFoTpJZR+UOCvhGGK6Nq8OWgh4K3OHAIeJB7xjGI8R3YTHkWtqhgQZAmMCbjxQHASqbfgYAFrMwvajnHWUpKtULLt1h4h6VDKoCE7yWyTGiF/8jQ4jDswlwfkRKZhG08AFtQQWf0ow3ojuZzz2SnmzV31zK73hLTuDHBCr3tjMAV69ErdK15FAvgCdlfQS1/MCNOsVcYRhpsNV79Qt644oS7yOh4uJglh9bx49cd1BiEremzsbxNK2MA2s6RmW0dG2ROYeHNXpcowPJIfuKFdHtDhTyza8qLQEiFAGYG64lJ87Hm4SYOT59aoAT7l3wSM+U9uTC8+PS/OyBTfanFe8jJ5L9OVL6v6SRzhLOPxrgcjSCn9HkUIzpRMlxnY4RMFVQ/tdpLl5s/9GRoEk2P3gimIgNlkzid6EzJ3XfcOmxm95RMbH2bBAg4a8qegFT4Q1+j2NnJ4f3AW8e20LQ3x4lPjz+MYtIdLeXLemiIEo2UECsTWU=
  - secure: fVf1QTPl1+RWTLO1SCSGglXIgzhQVKBGRqNovE2vJRIxCNqV+qYTXXw/LG3OC3KxMYoyOtV26RTM6CpRqb8ZDn3+1UTi2XRJqtad+CKpPxLn6aWd3wy2lo+FmzAFeHS80LtH/kDumY7joBY6uDQht2buN7k48ZOmydVfQjWxvWfic6AhgjSaAOPWCvVyMiyVRxBeANRzq3Cn63756zgkHTEKndY1t2tskLlKFZYXu0Omx0FTc9hBEIl1aU6U3TKV0Rnn5i7NN6ezTLW9oqAOJUAha/Z8E06a1SO+GDR0bgmgRySOBFgJXaDuYRgyH5sDTzvFZYTCZSagfcAmPWavT3zoW/6X2BVGRCF46FbW9vfviZcQnoIkkHo6cS5DwFm9nH0hFV3T1ygGwdf5kVqPYZbEfoxzV5L3CGsBa5KM+ujugjPp60Fsg+Q5MhxmFlgk9f/39RdU7wvmZWrfL17mIc4S5Np/0FwRcbHHbJrXnC3RG5cWG39QPzeiyyWFyA8+1NkgkfP+EHvyTCfxo8wTqplfD0mYAoPAvzbWv4QZRXSjnxdhyKGJ/poMNkSK6FGomIXipd6C2i1VbBu8YkeOTS3kadwBtZtrZG+Z0g+2WibkoHcKIG/0HM67qMSaHEdvW9qsMSdIUR8c9YPlcVy/4FQs6WDc8ybmwTGH1lpFIfg=
  - secure: vEAs85h+3982ndXYR2WNJ1fqhmkvq82ADOYp4DdXAWV2pKQOrVrjZoUyvDpMljJ58UDMlUQtIeohw5q+hacrw8yHNCSlAXG7tQ1Nt+C/q6zgbNj+UnrbuanR4lc2DDUFJ5AN6HjAEVyxXRLkggn0vcwLjaOTq/n9HgXiXIZrnXCeevAA5qPDDmc6PZERwDlaQdGfcggTbLSkI2dktZ6ucka1rrIrhwSzfzGy2TRfySBrV81cXGqR0tRWtWCMBJg9oVTgOJ0tUMqMRd52KXkmHZO7LSxSR08ZdcKawNXbXLg3H54CUVG+YziSXbdD1+dKbkjqOkBwR8P7nqFYa64MMAP8gUbtucPhW0pXZClbHYRlrEHesP1keS2R1B43hgpQLw3IU3x1r/AEwyHYiovuQJmp2Oo2kcvoSzJKTwys0rvNgY4uM6bi3/fyODB5GHTBz2OW7BPoaHJJIgAPz2tu4rcq5XCxhKuqaBK/PXXEJXzvGtL0AkKDMnbmqt+MR5SUOlnKVDYpTzamnhRZOFxcjrAOt+5y1TDCApJNWNXr/EoxD0yNp+8J2hPz40lZo+3yqga+elBHAWTkfflJ+tx+r/uDAfQhnHrBu6QVMOWejWktHGv6gEsawf8HTG+TtOGn3hpYAwQCgEJH9TSZHpZtqJIZAZvUFCryB89qjrMzRIU=
  - secure: igx4biTUX8vlp3bW+BasJs5uCAvZpXDdNdFmyUeglwenS3NKAu0Y1fLiL+P0vv5sBNYx/8ABnKzy2y+1nTlEOSLSjd/O6Lcy2BLeifRfsJVmjrM8hHNChFpAObl36GmWCuoUBHiAnxGcobhw+wdtbwXLldFPK+aGjrVpJGz0fxacGH5taDfQJZbZQAuwSf8mBowTbV/qtSt0ARxoI3sNRW6gt0+xZ4fyhDw7rQFfoVDngWZ+HpdH9osKBT1Bbtf3RihXWrSicqRIKBnEVW5yAkz0gpB7jVDUOSOQ97J96Oor6MvgFTSIcx4uCCbI7DEZrT8Q9e4TjNpMBvgOuycV8ExqCBbtnkUvi30sLdaVmwz6ReOAKo2gf2jo/OQvM9y1Qy242boweRgSSk5PdA8CgaM1T4fAao+xmIAdQRlS9LiJ/Bb7eqXZ4zXWwo7mXS56mInEFGDWff4TYAvtjMpnc3zFKUT8dICKmBI6OAPhxXzKkGvQamyMbM08pEzTVq1J70wh97q5vxt7LYv8JM07rc9uGmQw020asn7iAkOso78ifugXn7IsO86NR6enQkLLPXcF1oSFDnTgImozOxtjPimQEz17DttX2iGasjQIo0EBCItJJ90V6l5NNMsc6vs3O3M5l0TniyMrKPe6Gq8NhljK58921Hh8mS+55bg73yE=
before_install:
- export COVERALLS_PARALLEL=true
- export GOMAXPROCS=1
- export GITHUB_TOKEN=$GITHUB_TOKEN_RELEASE
- go get github.com/mattn/goveralls
script:
- make test-docker
- "$GOPATH/bin/goveralls -repotoken $COVERALLS -coverprofile=profile.cov -service=travis-ci"
- make build
- test -f bin/linux-amd64/server
- make container
- docker images | grep meio/go-swap-server

deploy:
- provider: script
  skip_cleanup: true
  script: ./scripts/build-docker.sh
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

notifications:
  webhooks:
    urls: https://coveralls.io/webhook?repo_token=$COVERALLS
